exception.id_not_found=ID: {0} wasn`t found.